extends Node

signal main_menu_done

signal shake_requested
signal player_kill_started
signal player_dissolve_started
signal player_dissolved
signal player_killed
signal player_entered_exit_portal
signal key_obtained
