extends Node

signal main_menu_done
signal story_done
signal game_over_done
signal go_to_main_menu

signal shake_requested
signal player_kill_started
signal player_dissolve_started
signal player_dissolved
signal player_killed
signal player_entered_exit_portal
signal player_won
signal key_obtained
signal loop_timer_updated
